services:
  backend:
    build:
      context: ../.
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
#    environment:
#    command: flask run --host=0.0.0.0

#  frontend:
#    build:
#      context: frontend
#    ports:
#      - "3000:3000"
#    command: yarn start
#    depends_on:
#      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logiqube
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: